### ISSUE TITLE
Порядок выполнения

### ISSUE THREAD

**Issue by victor-yacovlev** [mipt-proglang-2015/proglangs-popov#2]
1. Создать модуль:

```
PyObject *mainModule = PyImport_AddModule("__main__");
```
1. Скомпилировать текст в объектный байт-код:

```
code = Py_CompileString(...)
```
1. Выполнить код; PyEval_EvalCode возвращает PyObject - результат

```
PyEval_EvalCode(code)
```

**Comment by ShmaxPPS** [comment]
@victor-yacovlev 
Сделал как написано.
